version: "3.8"

services:
  db:
    container_name: library-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bestPassword123
      - POSTGRES_DB=library
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
